{
    'name': 'POS Vendor Bills & Purchase Orders',
    'version': '1.0',
    'category': 'Point of Sale / Purchase',
    'depends': [
        'purchase',
        'account',
        'stock',
        'base',
        'point_of_sale',
        'account_invoice_supplier_ref_unique',
        'account_invoice_supplierinfo_update',
        'account_invoice_date_due',
        'account_maturity_date_default',
        'partner_statement',
        'account_financial_report',
    ],
    'data': [
        'security/ir.model.access.csv',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}